imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        
        - TSAppBundle
        - TSUserBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:
            bin: /usr/bin/sass
        compass:
            bin: /usr/bin/compass
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: ssl
    auth_mode:  login
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TS\UserBundle\Entity\User
    registration:
        form:
            type: ts_userbundle_user
    

simple_things_entity_audit:
    audited_entities:
        - TS\AppBundle\Entity\Product
        - TS\AppBundle\Entity\Event
        - TS\AppBundle\Entity\CommentEvent
        - TS\AppBundle\Entity\CommentProduct
        - TS\AppBundle\Entity\ContentEvent
        - TS\AppBundle\Entity\ContentProduct
        - TS\AppBundle\Entity\EventProduct
        - TS\AppBundle\Entity\EventUser
        - TS\AppBundle\Entity\ProductUser
        - TS\UserBundle\Entity\User
    global_ignore_columns:
        - createdAt
        - updatedAt
        - password

                
# app/config/config.yml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
                
endroid_qr_code:
    size: 100
    padding: 10
    extension: gif
    error_correction_level: low
    foreground_color: { r: 0, g: 0, b: 0, a: 0 }
    background_color: { r: 255, g: 255, b: 255, a: 0 }


# Vich Uploader
vich_uploader:
    db_driver: orm

    mappings:
        photo:
            uri_prefix:         /images
            upload_destination: %kernel.root_dir%/../web/images
            namer:              vich_uploader.namer_uniqid

