# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    "random_factory":
        class:     "RandomLib\Factory"
        public:    false
    "random_strength":
        class:      "SecurityLib\Strength"
        arguments:   [ 5 ] # SecurityLib\Strength::MEDIUM
        public:     false
    "random_generator":
        class:              "RandomLib\Generator"
        factory_service:    random_factory
        factory_method:     getGenerator
        arguments:          [ @random_strength ]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
    ts_app.doctrine.notification:
        class: TS\AppBundle\DoctrineListener\UserQrCodeCreation
        arguments: [@random_generator]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    ts_userbundle_user:
        class: TS\UserBundle\Form\UserType
        tags:
            - { name: form.type }
        arguments: [%fos_user.model.user.class%]
   
