<?php

namespace TS\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TS\AppBundle\Entity\Event;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{   
    /**
     * Gets a QueryBuilder finding an enabled Duraltag by QrCode.
     *
     * @param $userId
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getRoot()
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.name = :name')
            ->setParameter('event', 'Femme')
            
        ;
        }
 
    
}
