<?php

namespace TS\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TS\AppBundle\Entity\User;
/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
     /**
     * Gets a QueryBuilder finding an enabled Duraltag by QrCode.
     *
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderEnabledFuture()
    {
        return $this
            ->createQueryBuilder('e')
            ->where('e.enabled = :true')
            //->andWhere('e.dateevent > :today')
            ->setParameter('true', true)
        ;
        }
    
    /**
     * Finds a Duraltag with its associated EAN by its QR code if the associated retailer is enabled.
     *
     *
     * @return Event
     */
    public function findEventstWithUserData()
    {
        $results = $this
            ->getQueryBuilderEnabledFuture()
            ->select('e, eu')
            ->leftJoin('e.eventUsers', 'eu')
            //->leftJoin('eu.user', 'u')
            //->orderBy('e.dateEvent', 'ASC')
            ->getQuery()
            ->getResult();

        return $results;
    }
}
